# Permalinks
permalink:           pretty

# Setup
title:               Sean P. Davern
tagline:             Living in the Grey
url:                 http://spdavern.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sean Davern
  url:               https://twitter.com/seanpdavern
  email:             sean@lizandsean.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/spdavern

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
